
spring:
  application:
    name: library
  threads:
    virtual:
      enabled: true
  data:
   mongodb:
      host: 'localhost'
      port: 27017
      database: 'library'
      
server:
  servlet:
    context-path: '/library/api'
   