
spring:
  application:
    name: library
  threads:
    virtual:
      enabled: true
  data:
   mongodb:
      host: 'localhost'
      port: 27017
      database: 'library'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: localhost:8080/library/api/auth
server:
  servlet:
    context-path: '/library/api'
    
logging:
  level:
    org:
      springframework:
        security:
          DEBUG
    ch:
      fhnw:
        library:
          DEBUG
   
jwt:
  secret: your-very-long-secure-key-that-is-at-least-32-characters
  expiration: 
    access-token: 3600000
    refresh-token: 604800000
    
images:
  dir: "images/"